### ISSUE TITLE
Height visualization not working

### ISSUE THREAD

**Issue by hfu** [ubukawa/cartotile_trial#4]
somehow managed to change the color and display label, but did not with the height expression.

**Comment by hfu** [comment]
Confirmed a reference error from https://ubukawa.github.io/cartotile_trial/who_practice/docs/#0.44/9.3/13.5. 

![ 2020-06-03 9 46 33](https://user-images.githubusercontent.com/18297/83583380-22b5f080-a57f-11ea-8e78-c406545e1e60.jpg)

**Comment by ubukawa** [comment]
Oh, thank you!!
I added "let ISO_A2," then it works properly. Wow!!

Even the ISO_A2 comes from map, it is needed to be defined. I see it. Thank you.
