### ISSUE TITLE
Remove the duplication of map labels

### ISSUE THREAD

**Issue by hfu** [ubukawa/cartotile_trial#5]
multiple polygons and separation of data by tiles at larger scales.

**Comment by hfu** [comment]
In short, the technically correct solution is

> Have label point data separately; you can calculate it from the source data. 

It is not a good idea to create labels from polygons that can cross the boundary of tiles. 

You can also think about the case of Rome and Vatican for example. Label issues are better solved in the data level rather than in the rendering stage. 

Yet there may be some options to eliminate the overwrap of labels if you look into Mapbox GL JS documentation.

**Comment by ubukawa** [comment]
Thank you. I will do so.
